version: '3'
services:
  web:
    build: .
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - 3000:3000
    depends_on:
      - db
      - selenium_chrome
    tty: true
    stdin_open: true
    # environment:
      # - SERVER_HOST=selenium_chrome
      # - SERVER_PORT=4444
    #   SELENIUM_DRIVER_URL: http://selenium-chrome:4444/wd/hub
  selenium_chrome:
    image: selenium/standalone-chrome:latest
    shm_size: 2gb
    ports:
      - 4444:4444
      - 7900:7900
  db:
    image: mysql:latest
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - db-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      TZ: "Asia/Tokyo"
    ports:
      - "3306:3306"

volumes:
  db-volume: